### ISSUE TITLE
autoproperty and typescript 2.3.4

### ISSUE THREAD

**Issue by st-clair-clarke** [nickwinger/autoproperty#1]
Hi, Do you know if autoproperty works with typescript 2.3.4? Can't seem to get it to work.

Thanks

**Comment by nickwinger** [comment]
Hi,

i just updated to 2.3.4 and ran the tests without problems, can you please post your code and describe the problem a little more ?

**Comment by st-clair-clarke** [comment]
Hi Nick,
On a closer look here is what actually caused the issue for me.

Consider the following:

```
    p.propertyChanged.subscribe((args: PropertyChangedEventArgs) => {
        console.log(args.propertyName + ' changed from ' + args.oldValue + ' to ' + args.newValue);
    });
```

Note that p.propertyChanged... that should actually be p.$propertyChanged... gleaned from your source.
So the documentation at the site needs a little correction.

This is just an observation too.

Observables are usually named with the $ at the end of the variable, so $propertyChanged in this would be propertyChanged$. Any reason why it is reversed?

Helpful package still.

Cheers

**Comment by nickwinger** [comment]
Hi,

thanks for pointing that out, i corrected the documentation.
Actually angular1 also prefixes meta properties with $, so i did i that way.

Cheers,
Nick
